name: Daily TikTok Mailer

on:
  schedule:
    - cron: '0 12 * * 1-5'   # 10:00 AM Argentina (UTC-3), lunes a viernes
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar dependencias
        run: pip install -r requirements.txt

      - name: Ejecutar el script
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
          EMAIL_USER_TIKTOK: ${{ secrets.EMAIL_USER_TIKTOK }}
          EMAIL_PASS_TIKTOK: ${{ secrets.EMAIL_PASS_TIKTOK }}
          EMAIL_TO: ${{ secrets.EMAIL_TO }}
        #run: python mailer_NUEVO_tiktok.py
