name: Enviar Correos Diarios

on:
  schedule:
    # Corre a las 9:00 AM en Argentina (12:00 UTC)
    - cron: '0 12 * * *'
    # Corre a la 1:00 PM en Argentina (16:00 UTC)
    - cron: '0 16 * * *'
    # Corre a las 6:00 PM en Argentina (21:00 UTC)
    - cron: '0 21 * * *'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  send_email:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Instalar dependencias
        run: |
          pip install -r requirements.txt

      - name: Ejecutar envío de correo
        run: python send_email.py
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          EMAIL_TO: ${{ secrets.EMAIL_TO }}
          NEWS_QUERY: ${{ secrets.NEWS_QUERY }}
