name: Send News Emails IRSA

on:
  schedule:
    - cron: "0 11 * * *"   # 08:00 Buenos Aires (UTC+3)
    - cron: "0 16 * * *"   # 13:00 Buenos Aires
    - cron: "0 21 * * *"   # 18:00 Buenos Aires
  workflow_dispatch:

jobs:
  mailer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run mailer
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          EMAIL_TO_IRSA : ${{ secrets.EMAIL_TO_IRSA }}
        run: python mailer_irsa.py
