name: Run News Scraper

on:
  schedule:
    - cron: "*/50 * * * *"   # cada hora en el minuto 0
  workflow_dispatch:      # permite correrlo manualmente también

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
          APIFY_TOKEN: ${{ secrets.APIFY_TOKEN }}
        run: python scraper.py
