name: Run Scraper Hourly

on:
  schedule:
    - cron: "0 * * * *"   # cada hora en UTC
  workflow_dispatch:

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    env:
      APIFY_TOKEN: ${{ secrets.APIFY_TOKEN }}
      ACTOR_ID: ${{ secrets.APIFY_ACTOR_ID }}
      NEWS_QUERY: "tiktok"

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scraper
        run: python scraper.py

      - name: Upload CSV artifact
        uses: actions/upload-artifact@v4
        with:
          name: news-csv
          path: news_results.csv
