name: Scrape and Send News

on:
  schedule:
    - cron: "0 * * * *"  # Cada hora (UTC)
  workflow_dispatch:

jobs:
  scrape-and-email:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    env:
      APIFY_TOKEN: ${{ secrets.APIFY_TOKEN }}
      ACTOR_ID: ${{ secrets.APIFY_ACTOR_ID }}
      EMAIL_USER: ${{ secrets.EMAIL_USER }}
      EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
      EMAIL_TO: ${{ secrets.EMAIL_TO }}
      NEWS_QUERY: "tiktok"
      MAX_PER_COUNTRY: "100"

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ejecutar scraper
        run: python scraper.py

      - name: Commit results
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add news_results.csv
          git commit -m "Update results [skip ci]" || echo "No changes"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:${{ github.ref }}

      - name: Ejecutar envío de correo (si corresponde)
        run: python send_email.py
