name: Newsletter Scraper

on:
  schedule:
    # Este cron se ejecuta cada hora
    - cron: '0 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run scraper
        run: |
          python scraper.py
        env:
          APIFY_TOKEN: ${{ secrets.APIFY_TOKEN }}
          ACTOR_ID: ${{ secrets.APIFY_ACTOR_ID }}

      - name: Commit and push new results
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "feat: Add new scraped news results"
          file_pattern: "news_results.csv"
          commit_author: "GitHub Actions <actions@github.com>"
          skip_dirty_check: false
