name: Send News Emails (ART schedule)

on:
  schedule:
    - cron: "0 11 * * *"  # 08:00 ART = 11:00 UTC
    - cron: "0 15 * * *"  # 12:00 ART = 15:00 UTC
    - cron: "0 18 * * *"  # 15:00 ART = 18:00 UTC
    - cron: "0 21 * * *"  # 18:00 ART = 21:00 UTC
    - cron: "0 23 * * *"  # 20:00 ART = 23:00 UTC
  workflow_dispatch:

jobs:
  send-email:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Send email
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          EMAIL_TO: ${{ secrets.EMAIL_TO }}
          NEWS_QUERY: "tiktok"
        run: python send_email.py
